apiVersion: maestro.k8s.io/v1alpha1
kind: Framework
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: flink-financial-demo
---
apiVersion: maestro.k8s.io/v1alpha1
kind: FrameworkVersion
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: flink-financial-demo
  namespace: default
spec:
  framework:
    name: flink-financial-demo
    kind: Framework
  # Add fields here
  parameters:
  - name: DOWNLOAD_URL
    description: URL To download the application from
    default: "https://downloads.mesosphere.com/dcos-demo/flink/flink-job-1.0.jar"
  templates:
    zookeeper.yaml: |
      apiVersion: maestro.k8s.io/v1alpha1
      kind: Instance
      metadata:
        labels:
          controller-tools.k8s.io: "1.0"
          framework: zookeeper
        name: zk
      spec:
        frameworkVersion:
          name: zookeeper-1.0
          namespace: default
          type: FrameworkVersions
        # Add fields here
        name: "zk"
        parameters:
          ZOOKEEPER_CPUS: "0.3"
    kafka.yaml: |
      apiVersion: maestro.k8s.io/v1alpha1
      kind: Instance
      metadata:
        labels:
          controller-tools.k8s.io: "1.0"
          framework: kafka 
        name: kafka
      spec:
        frameworkVersion:
          name: kafka-2.11-2.4.0
          namespace: default
          type: FrameworkVersion
        parameters:
          KAFKA_ZOOKEEPER_URI: "{{NAME}}-zk-{{NAME}}-zk-0.{{NAME}}-zk-hs:2181,{{NAME}}-zk-{{NAME}}-zk-1.{{NAME}}-zk-hs:2181,{{NAME}}-zk-{{NAME}}-zk-2.{{NAME}}-zk-hs:2181"
          KAFKA_ZOOKEEPER_PATH: "/kafka"
          BROKER_COUNT: "3"
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    flink.yaml: |
      apiVersion: maestro.k8s.io/v1alpha1
      kind: Instance
      metadata:
        labels:
          controller-tools.k8s.io: "1.0"
          framework: flink 
        name: flink
      spec:
        frameworkVersion:
          name: flink
          namespace: default
          type: FrameworkVersion
    generator.yaml: |
      apiVersion: apps/v1beta1
      kind: Deployment
      metadata:
        name: generator
      spec:
        replicas: 1
        template:
          metadata:
            name: flink-demo-generator
            labels:
              app: flink-demo-generator
          spec:
            containers:
            - name: flink-demo-generator
              image: mesosphere/flink-generator:0.1
              command: ["/generator-linux"]
              imagePullPolicy: Always
              args: ["--broker", "{{NAME}}-kafka-kafka-0.{{NAME}}-kafka-svc:9093"]
    actor.yaml: |
      apiVersion: apps/v1beta1
      kind: Deployment
      metadata:
        name: actor
      spec:
        replicas: 1
        template:
          metadata:
            name: flink-demo-actor
            labels:
              app: flink-demo-actor
          spec:
            containers:
            - name: actor
              image: runyonsolutions/flink-actor:0.1
              command: ["/fraudDisplay-linux"]
              imagePullPolicy: Always
              args: ["--broker", "{{NAME}}-kafka-kafka-0.{{NAME}}-kafka-svc:9093"]
    uploader.yaml: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        namespace: default
        name: upload-job
      spec:
        template:
          metadata:
            name: {{PLAN_NAME}}-job
          spec:
            restartPolicy: OnFailure
            containers:
            - env:
              - name: DOWNLOAD_URL
                value: {{DOWNLOAD_URL}}
              - name: JOBMANAGER
                value: {{NAME}}-flink-jobmanager
              name: {{PLAN_NAME}}
              image: runyonsolutions/flink-uploader
              imagePullPolicy: Always
  tasks:
    kafka:
      resources:
      - kafka.yaml
    zookeeper:
      resources:
      - zookeeper.yaml
    flink:
      resources:
      - flink.yaml
    generator:
      resources:
      - generator.yaml
    actor:
      resources:
      - actor.yaml
    upload:
      resources:
      - uploader.yaml
  plans:
    deploy:
      strategy: serial
      phases:
        - name: dependencies
          strategy: serial
          steps:
            - name: zookeeper
              tasks:
              - zookeeper
            - name: kafka
              tasks:
              - kafka
        - name: flink-cluster
          strategy: serial
          steps:
            - name: flink
              tasks:
              - flink
        - name: demo
          strategy: serial
          steps:
            - name: gen
              tasks:
              - generator
            - name: act
              tasks:
              - actor
    upload:
      strategy: serial
      phases:
        - name: dependencies
          strategy: serial
          steps:
            - name: upload
              tasks:
              - upload
---
apiVersion: maestro.k8s.io/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    framework: flink-financial-demo
  name: demo
spec:
  frameworkVersion:
    name: flink-financial-demo
    namespace: default
    type: FrameworkVersion
  parameters:
    NONE: "true"